Import("*")

SimObject("CimHandler.py", sim_objects=["CimHandler"])
SimObject(
    "CimOperationInterface.py",
    sim_objects=["CimOperationInterface", "CimFaultInjection"],
)

Source("cim_handler.cc")
Source("cim_operation_interface.cc")
Source("cim_fault_injection.cc")

DebugFlag("CIMDBG")


